// function Products() {
    let Products = [
            // Samsung
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s721blbcpkd/gallery/pk-galaxy-s24-fe-s721-sm-s721blbcpkd-thumb-543637923?$152_152_PNG$",
              name: "Samsung Galaxy S24 FE",
              description:
                "Samsung Galaxy S24 FE offers a premium smartphone experience with a vibrant 6.4-inch display and a versatile 50MP triple-camera setup, powered by the Exynos 2200 chip. It's perfect for photography enthusiasts and daily users alike.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 160,000",
              display: "6.4 inch",
              camera: "50MP Triple",
              battery: "4500mAh",
              processor: "Exynos 2200",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s921bzacpkd/gallery/pk-galaxy-s24-488994-sm-s921bzacpkd-thumb-539767822?$152_152_PNG$",
              name: "Samsung Galaxy S24",
              description:
                "The Galaxy S24 features a cutting-edge design and powerful Snapdragon 8 Gen 2 processor. Its 6.1-inch Dynamic AMOLED display and versatile camera system make it a standout device for any user.",
              ram: "8GB",
              rom: "256GB",
              price: "PKR 200,000",
              display: "6.1 inch",
              camera: "50MP Triple",
              battery: "3900mAh",
              processor: "Snapdragon 8 Gen 2",
              year: "2024",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s928blbqpkd/gallery/pk-galaxy-s24-s928-519417-sm-s928blbqpkd-thumb-543035389?$152_152_PNG$",
              name: "Samsung Galaxy S24 Ultra",
              description:
                "Designed for professionals, the Galaxy S24 Ultra boasts a massive 6.8-inch QHD+ display and a stunning 200MP camera. With S Pen functionality and Snapdragon 8 Gen 2 chip, it delivers unmatched performance.",
              ram: "12GB",
              rom: "512GB",
              price: "PKR 400,000",
              display: "6.8 inch",
              camera: "200MP Quad",
              battery: "5000mAh",
              processor: "Snapdragon 8 Gen 2",
              year: "2024",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a546elgdpkd/gallery/pk-galaxy-a54-5g-sm-a546-sm-a546elgdpkd-thumb-538125046?$152_152_PNG$",
              name: "Samsung Galaxy A54",
              description:
                "The Samsung Galaxy A54 features a large 6.4-inch Super AMOLED display with a 50MP camera, providing an excellent balance of performance and features for mid-range users.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 85,000",
              display: "6.4 inch",
              camera: "50MP Triple",
              battery: "5000mAh",
              processor: "Exynos 1380",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a346elgepkd/gallery/pk-galaxy-a34-5g-sm-a346-sm-a346elgepkd-thumb-538124879?$152_152_PNG$",
              name: "Samsung Galaxy A34",
              description:
                "With a 6.6-inch Super AMOLED display and a 48MP camera, the Galaxy A34 provides an excellent multimedia experience and is ideal for users seeking a solid smartphone without breaking the bank.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 70,000",
              display: "6.6 inch",
              camera: "48MP Triple",
              battery: "5000mAh",
              processor: "Dimensity 1080",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-f731bzaepkd/gallery/pk-galaxy-z-flip5-f731-472126-sm-f731bzaepkd-thumb-538236894?$152_152_PNG$",
              name: "Samsung Galaxy Z Flip 5",
              description:
                "The Samsung Galaxy Z Flip 5 features a compact design with a 6.7-inch foldable display. Powered by the Snapdragon 8 Gen 2 processor and equipped with a dual 12MP camera, it's perfect for users who value innovation.",
              ram: "8GB",
              rom: "256GB",
              price: "PKR 250,000",
              display: "6.7 inch",
              camera: "12MP Dual",
              battery: "3700mAh",
              processor: "Snapdragon 8 Gen 2",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-f946bzkgpkd/gallery/pk-galaxy-z-fold5-f946-472130-sm-f946bzkgpkd-thumb-538237573?$152_152_PNG$",
              name: "Samsung Galaxy Z Fold 5",
              description:
                "The Galaxy Z Fold 5 offers a unique folding design with a massive 7.6-inch AMOLED display. It’s powered by Snapdragon 8 Gen 2, making multitasking and productivity seamless.",
              ram: "12GB",
              rom: "512GB",
              price: "450,000 PKR",
              display: "7.6 inch",
              camera: "50MP Triple",
              battery: "4400mAh",
              processor: "Snapdragon 8 Gen 2",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/pk-galaxy-j4-sm-j410f-sm-j410fzbdpak-frontblue-thumb-138483698?$152_152_PNG$",
              name: "Samsung Galaxy M54",
              description:
                "The Galaxy M54 features a large 6.7-inch Super AMOLED display and a 108MP main camera, making it an excellent choice for multimedia and photography enthusiasts on a budget.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 90,000",
              display: "6.7 inch",
              camera: "108MP Triple",
              battery: "6000mAh",
              processor: "Exynos 1380",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s721blbcpkd/gallery/pk-galaxy-s24-fe-s721-sm-s721blbcpkd-thumb-543637923?$152_152_PNG$",
              name: "Samsung Galaxy S24 FE",
              description:
                "With a stunning 6.7-inch AMOLED display and a powerful 108MP camera, the Galaxy F54 delivers an exceptional photography experience and robust performance for everyday tasks.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 75,000",
              display: "6.7 inch",
              camera: "108MP Triple",
              battery: "6000mAh",
              processor: "Exynos 1380",
              year: "2023",
            },
            {
              img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a155fzyipkd/gallery/pk-galaxy-a15-sm-a155-sm-a155fzyipkd-thumb-539360558?$152_152_PNG$",
              name: "Samsung Galaxy A15",
              description:
                "The Galaxy A14 is a budget-friendly smartphone featuring a 6.6-inch display and a triple-camera setup. It offers a good balance of performance and features for everyday users.",
              ram: "4GB",
              rom: "128GB",
              price: "PKR 50,000",
              display: "6.6 inch",
              camera: "50MP Triple",
              battery: "5000mAh",
              processor: "Exynos 1330",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/4c/25/1e/4c251eafe5ce567d87d82da2b1acbed6.jpg",
              name: "iPhone 11",
              description:
                "iPhone 11 features a 6.1-inch Liquid Retina display and a dual-camera system with 12MP ultra-wide and wide lenses. Powered by the A13 Bionic chip, it offers excellent performance and battery life.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 130,000",
              display: "6.1 inch",
              camera: "12MP Dual",
              battery: "3110mAh",
              processor: "A13 Bionic",
              year: "2019",
            },
            {
              img: "https://i.pinimg.com/236x/6e/11/af/6e11af3517edff2ff1aeca18a5a8b9d5.jpg",
              name: "iPhone 12",
              description:
                "The iPhone 12 comes with a 6.1-inch Super Retina XDR display and is powered by the A14 Bionic chip. It features a dual-camera system with improved low-light performance.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 145,000",
              display: "6.1 inch",
              camera: "12MP Dual",
              battery: "2815mAh",
              processor: "A14 Bionic",
              year: "2020",
            },
            {
              img: "https://i.pinimg.com/236x/d3/59/d6/d359d63c2039892edcbd3b3f0eba9bd0.jpg",
              name: "iPhone 12 Pro",
              description:
                "With a 6.1-inch Super Retina XDR display, the iPhone 12 Pro features a triple-camera system with 12MP ultra-wide, wide, and telephoto lenses, allowing for versatile photography.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 195,000",
              display: "6.1 inch",
              camera: "12MP Triple",
              battery: "2815mAh",
              processor: "A14 Bionic",
              year: "2020",
            },
            {
              img: "https://i.pinimg.com/236x/1e/07/ac/1e07ac048f06212f57d10754e4e71b5d.jpg",
              name: "iPhone 12 Pro Max",
              description:
                "The iPhone 12 Pro Max boasts a massive 6.7-inch Super Retina XDR display and the most advanced camera system, perfect for professional photographers and videographers.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 215,000",
              display: "6.7 inch",
              camera: "12MP Triple",
              battery: "3687mAh",
              processor: "A14 Bionic",
              year: "2020",
            },
            {
              img: "https://i.pinimg.com/236x/be/a3/12/bea31296162a1c6d82f7cfa90a14d60b.jpg",
              name: "iPhone 13",
              description:
                "The iPhone 13 features a 6.1-inch Super Retina XDR display with improved brightness and a dual-camera system. The A15 Bionic chip enhances performance and battery life.",
              ram: "4GB",
              rom: "128GB",
              price: "165,000 PKR",
              display: "6.1 inch",
              camera: "12MP Dual",
              battery: "3240mAh",
              processor: "A15 Bionic",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/a3/c7/6f/a3c76f7a3b1146d8d09bd120339bae37.jpg",
              name: "iPhone 13 Pro",
              description:
                "With a 6.1-inch Super Retina XDR display and ProMotion technology, the iPhone 13 Pro features a triple-camera system for exceptional photography and video recording.",
              ram: "6GB",
              rom: "128GB",
              price: "225,000 PKR",
              display: "6.1 inch",
              camera: "12MP Triple",
              battery: "3095mAh",
              processor: "A15 Bionic",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/dc/22/35/dc2235bbb7c5ae968a36e4fd9f3e1941.jpg",
              name: "iPhone 14",
              description:
                "The iPhone 14 features a larger 6.1-inch Super Retina XDR display, improved battery life, and a dual-camera system for better low-light performance. It continues to deliver exceptional performance with the A15 Bionic chip.",
              ram: "6GB",
              rom: "128GB",
              price: "185,000 PKR",
              display: "6.1 inch",
              camera: "12MP Dual",
              battery: "3279mAh",
              processor: "A15 Bionic",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/99/45/13/99451353ca1e26b031f45d6434c86084.jpg",
              name: "iPhone 14 Pro",
              description:
                "The iPhone 14 Pro features a stunning 6.1-inch ProMotion display with a 120Hz refresh rate and a triple-camera system that includes a 48MP main sensor, offering incredible photography capabilities.",
              ram: "6GB",
              rom: "128GB",
              price: "250,000 PKR",
              display: "6.1 inch",
              camera: "48MP Triple",
              battery: "3200mAh",
              processor: "A16 Bionic",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/474x/a8/87/47/a887478703588600644fc578e461b950.jpg",
              name: "iPhone 15",
              description:
                "The iPhone 15 features an upgraded 6.1-inch Super Retina XDR display and improved battery life. It includes the new A16 Bionic chip, enhancing overall performance and efficiency.",
              ram: "6GB",
              rom: "128GB",
              price: "210,000 PKR",
              display: "6.1 inch",
              camera: "12MP Dual",
              battery: "3279mAh",
              processor: "A16 Bionic",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/6c/ec/23/6cec2393266d3cf7dd078991fb7b30fe.jpg",
              name: "iPhone 15 Pro",
              description:
                "The iPhone 15 Pro features a premium titanium design and a 6.1-inch ProMotion display. Its advanced triple-camera system with a 48MP main sensor delivers stunning photography and videography.",
              ram: "8GB",
              rom: "128GB",
              price: "300,000 PKR",
              display: "6.1 inch",
              camera: "48MP Triple",
              battery: "3200mAh",
              processor: "A17 Pro",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/474x/c1/a1/c1/c1a1c11477777f575f4f0c8483e40bf1.jpg",
              name: "Infinix Zero 40",
              description:
                "Infinix Zero 40 features a stunning 6.78-inch AMOLED display with a 108MP camera, offering exceptional photography and vibrant visuals. Powered by the MediaTek Dimensity 8020, it ensures smooth performance.",
              ram: "8GB",
              rom: "256GB",
              price: "PKR 70,000",
              display: "6.78 inch",
              camera: "108MP Triple",
              battery: "5000mAh",
              processor: "Dimensity 8020",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/ae/ab/28/aeab285a42e446e90df30e39d7fad26a.jpg",
              name: "Infinix Note 12",
              description:
                "Infinix Note 12 comes with a 6.7-inch AMOLED display and a 50MP triple-camera system, providing a great balance of performance and features for everyday users.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 55,000",
              display: "6.7 inch",
              camera: "50MP Triple",
              battery: "5000mAh",
              processor: "Helio G88",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/474x/68/df/09/68df09a8d0e94b03819cf5c88a16e403.jpg",
              name: "Infinix Hot 12",
              description:
                "The Infinix Hot 12 features a large 6.82-inch display with a 50MP camera and a large 5000mAh battery, making it an excellent choice for budget-conscious users who enjoy multimedia.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 35,000",
              display: "6.82 inch",
              camera: "50MP Dual",
              battery: "5000mAh",
              processor: "Unisoc T606",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/474x/ad/80/48/ad80489824e66e374062e98dc602bc1b.jpg",
              name: "Infinix GT 20 Pro PUBG",
              description:
                "Designed for gamers, the Infinix GT 20 Pro features a 6.67-inch display with a 120Hz refresh rate, a powerful 108MP camera, and a gaming-centric design for enhanced performance.",
              ram: "8GB",
              rom: "256GB",
              price: "PKR 85,000",
              display: "6.67 inch",
              camera: "108MP Triple",
              battery: "5000mAh",
              processor: "Dimensity 1200",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/b3/f5/ff/b3f5ff05d4cce2973bfc365be46d3362.jpg",
              name: "Infinix Smart 8 Plus",
              description:
                "The Infinix Smart 8 Plus offers a 6.6-inch display and a dual-camera setup, ensuring good performance for everyday tasks at an affordable price.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 30,000",
              display: "6.6 inch",
              camera: "13MP Dual",
              battery: "5000mAh",
              processor: "Helio G37",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/b3/fa/52/b3fa52cba737475b3edb01316998e244.jpg",
              name: "Infinix Hot 40 Pro",
              description:
                "The Infinix Hot 40 Pro features a large 6.82-inch display and a 50MP camera, combined with a large battery to keep you going all day.",
              ram: "4GB",
              rom: "128GB",
              price: "PKR 38,000",
              display: "6.82 inch",
              camera: "50MP Dual",
              battery: "6000mAh",
              processor: "Unisoc T606",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/474x/e8/c2/ed/e8c2ed39deeb6f40550aede866a828ed.jpg",
              name: "Infinix Note 40",
              description:
                "Infinix Note 40 comes with a 6.8-inch display and a 64MP triple-camera system, offering excellent multimedia capabilities and battery performance.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 60,000",
              display: "6.8 inch",
              camera: "64MP Triple",
              battery: "5000mAh",
              processor: "Dimensity 8020",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/db/f5/21/dbf521f6d9132f8705a8c15a51f797fa.jpg",
              name: "Infinix Zero 5G",
              description:
                "Infinix Zero 5G features a 6.78-inch display and a triple-camera system with a 48MP main sensor. It's equipped with a powerful Dimensity 900 processor for smooth multitasking.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 65,000",
              display: "6.78 inch",
              camera: "48MP Triple",
              battery: "5000mAh",
              processor: "Dimensity 900",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/474x/27/63/0c/27630c74916de7532b7ebe11136ade11.jpg",
              name: "Tecno Camon 30 Pro",
              description:
                "Tecno Camon 30 Pro features a 6.8-inch display with a 64MP quad-camera setup, designed for photography enthusiasts who want stunning low-light performance.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 55,000",
              display: "6.8 inch",
              camera: "64MP Quad",
              battery: "5000mAh",
              processor: "Helio G95",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/474x/fd/6a/d3/fd6ad38a5af323543f3166edd9cf5f4b.jpg",
              name: "Tecno Pova 6 Pro 5G",
              description:
                "Tecno Pova 6 Pro 5G comes with a 6.9-inch FHD+ display and a powerful 50MP main camera. It supports 5G connectivity for fast internet access.",
              ram: "8GB",
              rom: "256GB",
              price: "70,000 PKR",
              display: "6.9 inch",
              camera: "50MP Triple",
              battery: "6000mAh",
              processor: "Dimensity 800",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/474x/ee/16/99/ee16997f68722e61ef919f61fe3f2c53.jpg",
              name: "Tecno Spark 30C",
              description:
                "The Tecno Spark 30C features a 6.6-inch display and a 50MP dual-camera system, providing a good experience for everyday tasks and multimedia consumption.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 32,000",
              display: "6.6 inch",
              camera: "50MP Dual",
              battery: "5000mAh",
              processor: "Helio G37",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/736x/e5/66/8d/e5668d42285fcee0ad602d62ddbe3813.jpg",
              name: "Tecno Camon 30",
              description:
                "Tecno Camon 30 is equipped with a 6.6-inch display and a 50MP camera, designed for users who appreciate great photography at an affordable price.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 38,000",
              display: "6.6 inch",
              camera: "50MP Dual",
              battery: "5000mAh",
              processor: "Helio G85",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/474x/c5/1e/1b/c51e1b19b7f7a7d8699d36ed8c196d2c.jpg",
              name: "Tecno Spark Go 1",
              description:
                "The Tecno Spark Go 1 features a 6.5-inch display and a dual-camera setup, perfect for basic smartphone users looking for a budget-friendly option.",
              ram: "3GB",
              rom: "32GB",
              price: "PKR 25,000",
              display: "6.5 inch",
              camera: "13MP Dual",
              battery: "5000mAh",
              processor: "Helio A22",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/5f/7a/bd/5f7abd370e61406d4139515d41c0c6a3.jpg",
              name: "Tecno Spark 20C",
              description:
                "The Tecno Spark 20C offers a 6.6-inch display and a 13MP camera, making it suitable for users who want an affordable device for everyday use.",
              ram: "4GB",
              rom: "64GB",
              price: "PKR 28,000",
              display: "6.6 inch",
              camera: "13MP Dual",
              battery: "5000mAh",
              processor: "Helio G25",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/0a/16/81/0a168120f64931bb9f2a64d38b1bbfca.jpg",
              name: "Tecno Camon 19",
              description:
                "Tecno Camon 19 comes with a 6.8-inch display and a 64MP camera, designed for capturing beautiful moments with advanced photography features.",
              ram: "6GB",
              rom: "128GB",
              price: "PKR 45,000",
              display: "6.8 inch",
              camera: "64MP Triple",
              battery: "5000mAh",
              processor: "Helio G85",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/cc/c3/33/ccc333a3b3ac1014b08137416b4a4316.jpg",
              name: "Tecno Pova 5",
              description:
                "Tecno Pova 5 features a large 6.9-inch display and a powerful 50MP main camera, combined with a 6000mAh battery for extended usage.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 48,000",
              display: "6.9 inch",
              camera: "50MP Dual",
              battery: "6000mAh",
              processor: "Helio G99",
              year: "2023",
            },
            {
              img: "https://i.pinimg.com/236x/be/4c/fd/be4cfd7ed75981ca32d4686c695d18c3.jpg",
              name: "Xiaomi 12",
              description:
                "Xiaomi 12 features a 6.28-inch AMOLED display with a 50MP triple-camera system. Powered by the Snapdragon 8 Gen 1 chip, it delivers excellent performance and photography.",
              ram: "8GB",
              rom: "128GB",
              price: "PKR 150,000",
              display: "6.28 inch",
              camera: "50MP Triple",
              battery: "4500mAh",
              processor: "Snapdragon 8 Gen 1",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/79/0e/76/790e76bc061f72e9e64b1026c83af107.jpg",
              name: "Xiaomi 12 Pro",
              description:
                "With a stunning 6.73-inch AMOLED display, the Xiaomi 12 Pro offers a triple-camera system with a 50MP main sensor for exceptional photography.",
              ram: "12GB",
              rom: "256GB",
              price: "200,000 PKR",
              display: "6.73 inch",
              camera: "50MP Triple",
              battery: "4600mAh",
              processor: "Snapdragon 8 Gen 1",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/45/17/23/451723669761c8c2f9740b1ab83d341a.jpg",
              name: "Xiaomi Redmi Note 11",
              description:
                "Xiaomi Redmi Note 11 features a 6.43-inch AMOLED display and a 50MP quad-camera setup, offering great value for money and solid performance.",
              ram: "4GB",
              rom: "128GB",
              price: "35,000 PKR",
              display: "6.43 inch",
              camera: "50MP Quad",
              battery: "5000mAh",
              processor: "Snapdragon 680",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/6a/cc/e2/6acce24127ce962b877068f3d704c94a.jpg",
              name: "Xiaomi 11T Pro",
              description:
                "The Xiaomi 11T Pro comes with a 6.67-inch AMOLED display, a 108MP triple-camera system, and is powered by the Snapdragon 888 for high-end performance.",
              ram: "8GB",
              rom: "256GB",
              price: "175,000 PKR",
              display: "6.67 inch",
              camera: "108MP Triple",
              battery: "5000mAh",
              processor: "Snapdragon 888",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/474x/f3/03/2d/f3032d5b96ae0d25c9e04cbb3aae0b65.jpg",
              name: "Xiaomi Poco F4",
              description:
                "Xiaomi Poco F4 features a 6.67-inch AMOLED display, a 64MP triple-camera setup, and is powered by the Snapdragon 870, delivering top-notch performance for gaming.",
              ram: "8GB",
              rom: "256GB",
              price: "60,000 PKR",
              display: "6.67 inch",
              camera: "64MP Triple",
              battery: "4500mAh",
              processor: "Snapdragon 870",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/c7/e1/9b/c7e19b1d73c5cf6266071c070e597005.jpg",
              name: "Realme GT 2 Pro",
              description:
                "Realme GT 2 Pro features a 6.7-inch AMOLED display with a 50MP triple-camera system, offering flagship performance with the Snapdragon 8 Gen 1 chip.",
              ram: "8GB",
              rom: "256GB",
              price: "180,000 PKR",
              display: "6.7 inch",
              camera: "50MP Triple",
              battery: "5000mAh",
              processor: "Snapdragon 8 Gen 1",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/fe/cf/26/fecf261bc66f163954802af932f9bdce.jpg",
              name: "Realme 9 Pro+",
              description:
                "The Realme 9 Pro+ features a 6.4-inch AMOLED display and a 50MP camera with advanced imaging capabilities, powered by the MediaTek Dimensity 920.",
              ram: "8GB",
              rom: "128GB",
              price: "60,000 PKR",
              display: "6.4 inch",
              camera: "50MP Triple",
              battery: "4500mAh",
              processor: "Dimensity 920",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/474x/ab/ea/d0/abead0b6e89b9458fef609a2975d2493.jpg",
              name: "Realme Narzo 50",
              description:
                "Realme Narzo 50 comes with a 6.6-inch display and a 50MP camera, delivering good performance at an affordable price.",
              ram: "4GB",
              rom: "64GB",
              price: "25,000 PKR",
              display: "6.6 inch",
              camera: "50MP Dual",
              battery: "5000mAh",
              processor: "Helio G96",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/f5/ac/ec/f5acec511978363035ebcac3eed2b450.jpg",
              name: "Realme 8 Pro",
              description:
                "Realme 8 Pro features a 6.4-inch Super AMOLED display and a 108MP camera, making it a strong contender in the mid-range segment.",
              ram: "8GB",
              rom: "128GB",
              price: "45,000 PKR",
              display: "6.4 inch",
              camera: "108MP Quad",
              battery: "4500mAh",
              processor: "Snapdragon 720G",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/2f/97/34/2f9734ac888fca0cb90d7446bd772bd0.jpg",
              name: "Realme C31",
              description:
                "The Realme C31 features a 6.5-inch display and a triple-camera setup, offering good features for budget users.",
              ram: "3GB",
              rom: "32GB",
              price: "20,000 PKR",
              display: "6.5 inch",
              camera: "13MP Triple",
              battery: "5000mAh",
              processor: "Unisoc T612",
              year: "2022",
            },
          
            {
              img: "https://i.pinimg.com/236x/f5/8d/e7/f58de7b3afb855b872b9ab19b33a8adc.jpg",
              name: "OnePlus 10 Pro",
              description:
                "OnePlus 10 Pro features a 6.7-inch Fluid AMOLED display and a triple-camera setup, powered by the Snapdragon 8 Gen 1 for smooth performance.",
              ram: "8GB",
              rom: "128GB",
              price: "200,000 PKR",
              display: "6.7 inch",
              camera: "48MP Triple",
              battery: "5000mAh",
              processor: "Snapdragon 8 Gen 1",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/0e/9d/1d/0e9d1de36e58276adc1c1891359228a6.jpg",
              name: "OnePlus Nord 2",
              description:
                "OnePlus Nord 2 offers a 6.43-inch Fluid AMOLED display and a 50MP camera, balancing performance and price for mid-range users.",
              ram: "8GB",
              rom: "128GB",
              price: "55,000 PKR",
              display: "6.43 inch",
              camera: "50MP Triple",
              battery: "4500mAh",
              processor: "Dimensity 1200",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/02/99/32/029932d67d3100eba7a430db76763917.jpg",
              name: "OnePlus 9",
              description:
                "OnePlus 9 features a 6.55-inch Fluid AMOLED display and a Hasselblad camera partnership for stunning photography.",
              ram: "8GB",
              rom: "128GB",
              price: "150,000 PKR",
              display: "6.55 inch",
              camera: "48MP Triple",
              battery: "4500mAh",
              processor: "Snapdragon 888",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/42/f5/12/42f5122d3b928d121ec9c28e1af3d69c.jpg",
              name: "OnePlus 8T",
              description:
                "The OnePlus 8T comes with a 6.55-inch Fluid AMOLED display and a 48MP quad-camera system, delivering great performance with fast charging.",
              ram: "12GB",
              rom: "256GB",
              price: "90,000 PKR",
              display: "6.55 inch",
              camera: "48MP Quad",
              battery: "4500mAh",
              processor: "Snapdragon 865",
              year: "2020",
            },
            {
              img: "https://i.pinimg.com/474x/03/01/17/030117af6349c2ba3a6fa3e439a5ca9c.jpg",
              name: "OnePlus Nord CE 2",
              description:
                "OnePlus Nord CE 2 features a 6.43-inch AMOLED display and a 64MP camera, providing a great balance of features for a mid-range smartphone.",
              ram: "8GB",
              rom: "128GB",
              price: "42,000 PKR",
              display: "6.43 inch",
              camera: "64MP Triple",
              battery: "4500mAh",
              processor: "Dimensity 900",
              year: "2022",
            },
          
            {
              img: "https://i.pinimg.com/236x/7c/55/e1/7c55e15281e9fcb9d71de93fcea780fa.jpg",
              name: "Oppo Find X5 Pro",
              description:
                "Oppo Find X5 Pro features a 6.7-inch AMOLED display and a 50MP triple-camera setup. It's powered by the Snapdragon 8 Gen 1 for high-end performance.",
              ram: "12GB",
              rom: "256GB",
              price: "230,000 PKR",
              display: "6.7 inch",
              camera: "50MP Triple",
              battery: "5000mAh",
              processor: "Snapdragon 8 Gen 1",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/b5/64/01/b5640111602ae996fab5617f86741432.jpg",
              name: "Oppo Reno 8 Pro",
              description:
                "The Oppo Reno 8 Pro features a 6.7-inch AMOLED display and a 50MP camera with advanced imaging capabilities, powered by the MediaTek Dimensity 8100.",
              ram: "8GB",
              rom: "256GB",
              price: "80,000 PKR",
              display: "6.7 inch",
              camera: "50MP Triple",
              battery: "4500mAh",
              processor: "Dimensity 8100",
              year: "2022",
            },
            {
              img: "https://i.pinimg.com/236x/d9/ba/d8/d9bad87a011371ce280314b88ea2ce82.jpg",
              name: "Oppo A54",
              description:
                "Oppo A54 comes with a 6.51-inch display and a 13MP camera, providing good features for budget-conscious users.",
              ram: "4GB",
              rom: "128GB",
              price: "28,000 PKR",
              display: "6.51 inch",
              camera: "13MP Triple",
              battery: "5000mAh",
              processor: "Helio P35",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/2f/d9/90/2fd990d4805f640bae3572ec8ea43a94.jpg",
              name: "Oppo F19 Pro",
              description:
                "Oppo F19 Pro features a 6.43-inch AMOLED display and a 48MP camera, making it a solid mid-range option with good performance.",
              ram: "8GB",
              rom: "128GB",
              price: "40,000 PKR",
              display: "6.43 inch",
              camera: "48MP Quad",
              battery: "4310mAh",
              processor: "Helio P95",
              year: "2021",
            },
            {
              img: "https://i.pinimg.com/236x/66/4b/af/664baf101a3ec02c55ca217a0526ff27.jpg",
              name: "Oppo A74 5G",
              description:
                "The Oppo A74 5G features a 6.5-inch AMOLED display and a 48MP camera, offering 5G connectivity at an affordable price.",
              ram: "6GB",
              rom: "128GB",
              price: "45,000 PKR",
              display: "6.5 inch",
              camera: "48MP Triple",
              battery: "5000mAh",
              processor: "Snapdragon 480",
              year: "2021",
            },
          ];
          // return items;
// } 


// let items = [
//     // Samsung
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s721blbcpkd/gallery/pk-galaxy-s24-fe-s721-sm-s721blbcpkd-thumb-543637923?$152_152_PNG$",
//       name: "Samsung Galaxy S24 FE",
//       description:
//         "Samsung Galaxy S24 FE offers a premium smartphone experience with a vibrant 6.4-inch display and a versatile 50MP triple-camera setup, powered by the Exynos 2200 chip. It's perfect for photography enthusiasts and daily users alike.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 160,000",
//       display: "6.4 inch",
//       camera: "50MP Triple",
//       battery: "4500mAh",
//       processor: "Exynos 2200",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s921bzacpkd/gallery/pk-galaxy-s24-488994-sm-s921bzacpkd-thumb-539767822?$152_152_PNG$",
//       name: "Samsung Galaxy S24",
//       description:
//         "The Galaxy S24 features a cutting-edge design and powerful Snapdragon 8 Gen 2 processor. Its 6.1-inch Dynamic AMOLED display and versatile camera system make it a standout device for any user.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "PKR 200,000",
//       display: "6.1 inch",
//       camera: "50MP Triple",
//       battery: "3900mAh",
//       processor: "Snapdragon 8 Gen 2",
//       year: "2024",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s928blbqpkd/gallery/pk-galaxy-s24-s928-519417-sm-s928blbqpkd-thumb-543035389?$152_152_PNG$",
//       name: "Samsung Galaxy S24 Ultra",
//       description:
//         "Designed for professionals, the Galaxy S24 Ultra boasts a massive 6.8-inch QHD+ display and a stunning 200MP camera. With S Pen functionality and Snapdragon 8 Gen 2 chip, it delivers unmatched performance.",
//       ram: "12GB",
//       rom: "512GB",
//       price: "PKR 400,000",
//       display: "6.8 inch",
//       camera: "200MP Quad",
//       battery: "5000mAh",
//       processor: "Snapdragon 8 Gen 2",
//       year: "2024",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a546elgdpkd/gallery/pk-galaxy-a54-5g-sm-a546-sm-a546elgdpkd-thumb-538125046?$152_152_PNG$",
//       name: "Samsung Galaxy A54",
//       description:
//         "The Samsung Galaxy A54 features a large 6.4-inch Super AMOLED display with a 50MP camera, providing an excellent balance of performance and features for mid-range users.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 85,000",
//       display: "6.4 inch",
//       camera: "50MP Triple",
//       battery: "5000mAh",
//       processor: "Exynos 1380",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a346elgepkd/gallery/pk-galaxy-a34-5g-sm-a346-sm-a346elgepkd-thumb-538124879?$152_152_PNG$",
//       name: "Samsung Galaxy A34",
//       description:
//         "With a 6.6-inch Super AMOLED display and a 48MP camera, the Galaxy A34 provides an excellent multimedia experience and is ideal for users seeking a solid smartphone without breaking the bank.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 70,000",
//       display: "6.6 inch",
//       camera: "48MP Triple",
//       battery: "5000mAh",
//       processor: "Dimensity 1080",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-f731bzaepkd/gallery/pk-galaxy-z-flip5-f731-472126-sm-f731bzaepkd-thumb-538236894?$152_152_PNG$",
//       name: "Samsung Galaxy Z Flip 5",
//       description:
//         "The Samsung Galaxy Z Flip 5 features a compact design with a 6.7-inch foldable display. Powered by the Snapdragon 8 Gen 2 processor and equipped with a dual 12MP camera, it's perfect for users who value innovation.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "PKR 250,000",
//       display: "6.7 inch",
//       camera: "12MP Dual",
//       battery: "3700mAh",
//       processor: "Snapdragon 8 Gen 2",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-f946bzkgpkd/gallery/pk-galaxy-z-fold5-f946-472130-sm-f946bzkgpkd-thumb-538237573?$152_152_PNG$",
//       name: "Samsung Galaxy Z Fold 5",
//       description:
//         "The Galaxy Z Fold 5 offers a unique folding design with a massive 7.6-inch AMOLED display. It’s powered by Snapdragon 8 Gen 2, making multitasking and productivity seamless.",
//       ram: "12GB",
//       rom: "512GB",
//       price: "450,000 PKR",
//       display: "7.6 inch",
//       camera: "50MP Triple",
//       battery: "4400mAh",
//       processor: "Snapdragon 8 Gen 2",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/pk-galaxy-j4-sm-j410f-sm-j410fzbdpak-frontblue-thumb-138483698?$152_152_PNG$",
//       name: "Samsung Galaxy M54",
//       description:
//         "The Galaxy M54 features a large 6.7-inch Super AMOLED display and a 108MP main camera, making it an excellent choice for multimedia and photography enthusiasts on a budget.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 90,000",
//       display: "6.7 inch",
//       camera: "108MP Triple",
//       battery: "6000mAh",
//       processor: "Exynos 1380",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-s721blbcpkd/gallery/pk-galaxy-s24-fe-s721-sm-s721blbcpkd-thumb-543637923?$152_152_PNG$",
//       name: "Samsung Galaxy S24 FE",
//       description:
//         "With a stunning 6.7-inch AMOLED display and a powerful 108MP camera, the Galaxy F54 delivers an exceptional photography experience and robust performance for everyday tasks.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 75,000",
//       display: "6.7 inch",
//       camera: "108MP Triple",
//       battery: "6000mAh",
//       processor: "Exynos 1380",
//       year: "2023",
//     },
//     {
//       img: "https://images.samsung.com/is/image/samsung/p6pim/pk/sm-a155fzyipkd/gallery/pk-galaxy-a15-sm-a155-sm-a155fzyipkd-thumb-539360558?$152_152_PNG$",
//       name: "Samsung Galaxy A15",
//       description:
//         "The Galaxy A14 is a budget-friendly smartphone featuring a 6.6-inch display and a triple-camera setup. It offers a good balance of performance and features for everyday users.",
//       ram: "4GB",
//       rom: "128GB",
//       price: "PKR 50,000",
//       display: "6.6 inch",
//       camera: "50MP Triple",
//       battery: "5000mAh",
//       processor: "Exynos 1330",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/4c/25/1e/4c251eafe5ce567d87d82da2b1acbed6.jpg",
//       name: "iPhone 11",
//       description:
//         "iPhone 11 features a 6.1-inch Liquid Retina display and a dual-camera system with 12MP ultra-wide and wide lenses. Powered by the A13 Bionic chip, it offers excellent performance and battery life.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 130,000",
//       display: "6.1 inch",
//       camera: "12MP Dual",
//       battery: "3110mAh",
//       processor: "A13 Bionic",
//       year: "2019",
//     },
//     {
//       img: "https://i.pinimg.com/236x/6e/11/af/6e11af3517edff2ff1aeca18a5a8b9d5.jpg",
//       name: "iPhone 12",
//       description:
//         "The iPhone 12 comes with a 6.1-inch Super Retina XDR display and is powered by the A14 Bionic chip. It features a dual-camera system with improved low-light performance.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 145,000",
//       display: "6.1 inch",
//       camera: "12MP Dual",
//       battery: "2815mAh",
//       processor: "A14 Bionic",
//       year: "2020",
//     },
//     {
//       img: "https://i.pinimg.com/236x/d3/59/d6/d359d63c2039892edcbd3b3f0eba9bd0.jpg",
//       name: "iPhone 12 Pro",
//       description:
//         "With a 6.1-inch Super Retina XDR display, the iPhone 12 Pro features a triple-camera system with 12MP ultra-wide, wide, and telephoto lenses, allowing for versatile photography.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 195,000",
//       display: "6.1 inch",
//       camera: "12MP Triple",
//       battery: "2815mAh",
//       processor: "A14 Bionic",
//       year: "2020",
//     },
//     {
//       img: "https://i.pinimg.com/236x/1e/07/ac/1e07ac048f06212f57d10754e4e71b5d.jpg",
//       name: "iPhone 12 Pro Max",
//       description:
//         "The iPhone 12 Pro Max boasts a massive 6.7-inch Super Retina XDR display and the most advanced camera system, perfect for professional photographers and videographers.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 215,000",
//       display: "6.7 inch",
//       camera: "12MP Triple",
//       battery: "3687mAh",
//       processor: "A14 Bionic",
//       year: "2020",
//     },
//     {
//       img: "https://i.pinimg.com/236x/be/a3/12/bea31296162a1c6d82f7cfa90a14d60b.jpg",
//       name: "iPhone 13",
//       description:
//         "The iPhone 13 features a 6.1-inch Super Retina XDR display with improved brightness and a dual-camera system. The A15 Bionic chip enhances performance and battery life.",
//       ram: "4GB",
//       rom: "128GB",
//       price: "165,000 PKR",
//       display: "6.1 inch",
//       camera: "12MP Dual",
//       battery: "3240mAh",
//       processor: "A15 Bionic",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/a3/c7/6f/a3c76f7a3b1146d8d09bd120339bae37.jpg",
//       name: "iPhone 13 Pro",
//       description:
//         "With a 6.1-inch Super Retina XDR display and ProMotion technology, the iPhone 13 Pro features a triple-camera system for exceptional photography and video recording.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "225,000 PKR",
//       display: "6.1 inch",
//       camera: "12MP Triple",
//       battery: "3095mAh",
//       processor: "A15 Bionic",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/dc/22/35/dc2235bbb7c5ae968a36e4fd9f3e1941.jpg",
//       name: "iPhone 14",
//       description:
//         "The iPhone 14 features a larger 6.1-inch Super Retina XDR display, improved battery life, and a dual-camera system for better low-light performance. It continues to deliver exceptional performance with the A15 Bionic chip.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "185,000 PKR",
//       display: "6.1 inch",
//       camera: "12MP Dual",
//       battery: "3279mAh",
//       processor: "A15 Bionic",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/99/45/13/99451353ca1e26b031f45d6434c86084.jpg",
//       name: "iPhone 14 Pro",
//       description:
//         "The iPhone 14 Pro features a stunning 6.1-inch ProMotion display with a 120Hz refresh rate and a triple-camera system that includes a 48MP main sensor, offering incredible photography capabilities.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "250,000 PKR",
//       display: "6.1 inch",
//       camera: "48MP Triple",
//       battery: "3200mAh",
//       processor: "A16 Bionic",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/474x/a8/87/47/a887478703588600644fc578e461b950.jpg",
//       name: "iPhone 15",
//       description:
//         "The iPhone 15 features an upgraded 6.1-inch Super Retina XDR display and improved battery life. It includes the new A16 Bionic chip, enhancing overall performance and efficiency.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "210,000 PKR",
//       display: "6.1 inch",
//       camera: "12MP Dual",
//       battery: "3279mAh",
//       processor: "A16 Bionic",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/6c/ec/23/6cec2393266d3cf7dd078991fb7b30fe.jpg",
//       name: "iPhone 15 Pro",
//       description:
//         "The iPhone 15 Pro features a premium titanium design and a 6.1-inch ProMotion display. Its advanced triple-camera system with a 48MP main sensor delivers stunning photography and videography.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "300,000 PKR",
//       display: "6.1 inch",
//       camera: "48MP Triple",
//       battery: "3200mAh",
//       processor: "A17 Pro",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/474x/c1/a1/c1/c1a1c11477777f575f4f0c8483e40bf1.jpg",
//       name: "Infinix Zero 40",
//       description:
//         "Infinix Zero 40 features a stunning 6.78-inch AMOLED display with a 108MP camera, offering exceptional photography and vibrant visuals. Powered by the MediaTek Dimensity 8020, it ensures smooth performance.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "PKR 70,000",
//       display: "6.78 inch",
//       camera: "108MP Triple",
//       battery: "5000mAh",
//       processor: "Dimensity 8020",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/ae/ab/28/aeab285a42e446e90df30e39d7fad26a.jpg",
//       name: "Infinix Note 12",
//       description:
//         "Infinix Note 12 comes with a 6.7-inch AMOLED display and a 50MP triple-camera system, providing a great balance of performance and features for everyday users.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 55,000",
//       display: "6.7 inch",
//       camera: "50MP Triple",
//       battery: "5000mAh",
//       processor: "Helio G88",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/474x/68/df/09/68df09a8d0e94b03819cf5c88a16e403.jpg",
//       name: "Infinix Hot 12",
//       description:
//         "The Infinix Hot 12 features a large 6.82-inch display with a 50MP camera and a large 5000mAh battery, making it an excellent choice for budget-conscious users who enjoy multimedia.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 35,000",
//       display: "6.82 inch",
//       camera: "50MP Dual",
//       battery: "5000mAh",
//       processor: "Unisoc T606",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/474x/ad/80/48/ad80489824e66e374062e98dc602bc1b.jpg",
//       name: "Infinix GT 20 Pro PUBG",
//       description:
//         "Designed for gamers, the Infinix GT 20 Pro features a 6.67-inch display with a 120Hz refresh rate, a powerful 108MP camera, and a gaming-centric design for enhanced performance.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "PKR 85,000",
//       display: "6.67 inch",
//       camera: "108MP Triple",
//       battery: "5000mAh",
//       processor: "Dimensity 1200",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/b3/f5/ff/b3f5ff05d4cce2973bfc365be46d3362.jpg",
//       name: "Infinix Smart 8 Plus",
//       description:
//         "The Infinix Smart 8 Plus offers a 6.6-inch display and a dual-camera setup, ensuring good performance for everyday tasks at an affordable price.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 30,000",
//       display: "6.6 inch",
//       camera: "13MP Dual",
//       battery: "5000mAh",
//       processor: "Helio G37",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/b3/fa/52/b3fa52cba737475b3edb01316998e244.jpg",
//       name: "Infinix Hot 40 Pro",
//       description:
//         "The Infinix Hot 40 Pro features a large 6.82-inch display and a 50MP camera, combined with a large battery to keep you going all day.",
//       ram: "4GB",
//       rom: "128GB",
//       price: "PKR 38,000",
//       display: "6.82 inch",
//       camera: "50MP Dual",
//       battery: "6000mAh",
//       processor: "Unisoc T606",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/474x/e8/c2/ed/e8c2ed39deeb6f40550aede866a828ed.jpg",
//       name: "Infinix Note 40",
//       description:
//         "Infinix Note 40 comes with a 6.8-inch display and a 64MP triple-camera system, offering excellent multimedia capabilities and battery performance.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 60,000",
//       display: "6.8 inch",
//       camera: "64MP Triple",
//       battery: "5000mAh",
//       processor: "Dimensity 8020",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/db/f5/21/dbf521f6d9132f8705a8c15a51f797fa.jpg",
//       name: "Infinix Zero 5G",
//       description:
//         "Infinix Zero 5G features a 6.78-inch display and a triple-camera system with a 48MP main sensor. It's equipped with a powerful Dimensity 900 processor for smooth multitasking.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 65,000",
//       display: "6.78 inch",
//       camera: "48MP Triple",
//       battery: "5000mAh",
//       processor: "Dimensity 900",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/474x/27/63/0c/27630c74916de7532b7ebe11136ade11.jpg",
//       name: "Tecno Camon 30 Pro",
//       description:
//         "Tecno Camon 30 Pro features a 6.8-inch display with a 64MP quad-camera setup, designed for photography enthusiasts who want stunning low-light performance.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 55,000",
//       display: "6.8 inch",
//       camera: "64MP Quad",
//       battery: "5000mAh",
//       processor: "Helio G95",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/474x/fd/6a/d3/fd6ad38a5af323543f3166edd9cf5f4b.jpg",
//       name: "Tecno Pova 6 Pro 5G",
//       description:
//         "Tecno Pova 6 Pro 5G comes with a 6.9-inch FHD+ display and a powerful 50MP main camera. It supports 5G connectivity for fast internet access.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "70,000 PKR",
//       display: "6.9 inch",
//       camera: "50MP Triple",
//       battery: "6000mAh",
//       processor: "Dimensity 800",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/474x/ee/16/99/ee16997f68722e61ef919f61fe3f2c53.jpg",
//       name: "Tecno Spark 30C",
//       description:
//         "The Tecno Spark 30C features a 6.6-inch display and a 50MP dual-camera system, providing a good experience for everyday tasks and multimedia consumption.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 32,000",
//       display: "6.6 inch",
//       camera: "50MP Dual",
//       battery: "5000mAh",
//       processor: "Helio G37",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/736x/e5/66/8d/e5668d42285fcee0ad602d62ddbe3813.jpg",
//       name: "Tecno Camon 30",
//       description:
//         "Tecno Camon 30 is equipped with a 6.6-inch display and a 50MP camera, designed for users who appreciate great photography at an affordable price.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 38,000",
//       display: "6.6 inch",
//       camera: "50MP Dual",
//       battery: "5000mAh",
//       processor: "Helio G85",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/474x/c5/1e/1b/c51e1b19b7f7a7d8699d36ed8c196d2c.jpg",
//       name: "Tecno Spark Go 1",
//       description:
//         "The Tecno Spark Go 1 features a 6.5-inch display and a dual-camera setup, perfect for basic smartphone users looking for a budget-friendly option.",
//       ram: "3GB",
//       rom: "32GB",
//       price: "PKR 25,000",
//       display: "6.5 inch",
//       camera: "13MP Dual",
//       battery: "5000mAh",
//       processor: "Helio A22",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/5f/7a/bd/5f7abd370e61406d4139515d41c0c6a3.jpg",
//       name: "Tecno Spark 20C",
//       description:
//         "The Tecno Spark 20C offers a 6.6-inch display and a 13MP camera, making it suitable for users who want an affordable device for everyday use.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "PKR 28,000",
//       display: "6.6 inch",
//       camera: "13MP Dual",
//       battery: "5000mAh",
//       processor: "Helio G25",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/0a/16/81/0a168120f64931bb9f2a64d38b1bbfca.jpg",
//       name: "Tecno Camon 19",
//       description:
//         "Tecno Camon 19 comes with a 6.8-inch display and a 64MP camera, designed for capturing beautiful moments with advanced photography features.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "PKR 45,000",
//       display: "6.8 inch",
//       camera: "64MP Triple",
//       battery: "5000mAh",
//       processor: "Helio G85",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/cc/c3/33/ccc333a3b3ac1014b08137416b4a4316.jpg",
//       name: "Tecno Pova 5",
//       description:
//         "Tecno Pova 5 features a large 6.9-inch display and a powerful 50MP main camera, combined with a 6000mAh battery for extended usage.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 48,000",
//       display: "6.9 inch",
//       camera: "50MP Dual",
//       battery: "6000mAh",
//       processor: "Helio G99",
//       year: "2023",
//     },
//     {
//       img: "https://i.pinimg.com/236x/be/4c/fd/be4cfd7ed75981ca32d4686c695d18c3.jpg",
//       name: "Xiaomi 12",
//       description:
//         "Xiaomi 12 features a 6.28-inch AMOLED display with a 50MP triple-camera system. Powered by the Snapdragon 8 Gen 1 chip, it delivers excellent performance and photography.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "PKR 150,000",
//       display: "6.28 inch",
//       camera: "50MP Triple",
//       battery: "4500mAh",
//       processor: "Snapdragon 8 Gen 1",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/79/0e/76/790e76bc061f72e9e64b1026c83af107.jpg",
//       name: "Xiaomi 12 Pro",
//       description:
//         "With a stunning 6.73-inch AMOLED display, the Xiaomi 12 Pro offers a triple-camera system with a 50MP main sensor for exceptional photography.",
//       ram: "12GB",
//       rom: "256GB",
//       price: "200,000 PKR",
//       display: "6.73 inch",
//       camera: "50MP Triple",
//       battery: "4600mAh",
//       processor: "Snapdragon 8 Gen 1",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/45/17/23/451723669761c8c2f9740b1ab83d341a.jpg",
//       name: "Xiaomi Redmi Note 11",
//       description:
//         "Xiaomi Redmi Note 11 features a 6.43-inch AMOLED display and a 50MP quad-camera setup, offering great value for money and solid performance.",
//       ram: "4GB",
//       rom: "128GB",
//       price: "35,000 PKR",
//       display: "6.43 inch",
//       camera: "50MP Quad",
//       battery: "5000mAh",
//       processor: "Snapdragon 680",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/6a/cc/e2/6acce24127ce962b877068f3d704c94a.jpg",
//       name: "Xiaomi 11T Pro",
//       description:
//         "The Xiaomi 11T Pro comes with a 6.67-inch AMOLED display, a 108MP triple-camera system, and is powered by the Snapdragon 888 for high-end performance.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "175,000 PKR",
//       display: "6.67 inch",
//       camera: "108MP Triple",
//       battery: "5000mAh",
//       processor: "Snapdragon 888",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/474x/f3/03/2d/f3032d5b96ae0d25c9e04cbb3aae0b65.jpg",
//       name: "Xiaomi Poco F4",
//       description:
//         "Xiaomi Poco F4 features a 6.67-inch AMOLED display, a 64MP triple-camera setup, and is powered by the Snapdragon 870, delivering top-notch performance for gaming.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "60,000 PKR",
//       display: "6.67 inch",
//       camera: "64MP Triple",
//       battery: "4500mAh",
//       processor: "Snapdragon 870",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/c7/e1/9b/c7e19b1d73c5cf6266071c070e597005.jpg",
//       name: "Realme GT 2 Pro",
//       description:
//         "Realme GT 2 Pro features a 6.7-inch AMOLED display with a 50MP triple-camera system, offering flagship performance with the Snapdragon 8 Gen 1 chip.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "180,000 PKR",
//       display: "6.7 inch",
//       camera: "50MP Triple",
//       battery: "5000mAh",
//       processor: "Snapdragon 8 Gen 1",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/fe/cf/26/fecf261bc66f163954802af932f9bdce.jpg",
//       name: "Realme 9 Pro+",
//       description:
//         "The Realme 9 Pro+ features a 6.4-inch AMOLED display and a 50MP camera with advanced imaging capabilities, powered by the MediaTek Dimensity 920.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "60,000 PKR",
//       display: "6.4 inch",
//       camera: "50MP Triple",
//       battery: "4500mAh",
//       processor: "Dimensity 920",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/474x/ab/ea/d0/abead0b6e89b9458fef609a2975d2493.jpg",
//       name: "Realme Narzo 50",
//       description:
//         "Realme Narzo 50 comes with a 6.6-inch display and a 50MP camera, delivering good performance at an affordable price.",
//       ram: "4GB",
//       rom: "64GB",
//       price: "25,000 PKR",
//       display: "6.6 inch",
//       camera: "50MP Dual",
//       battery: "5000mAh",
//       processor: "Helio G96",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/f5/ac/ec/f5acec511978363035ebcac3eed2b450.jpg",
//       name: "Realme 8 Pro",
//       description:
//         "Realme 8 Pro features a 6.4-inch Super AMOLED display and a 108MP camera, making it a strong contender in the mid-range segment.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "45,000 PKR",
//       display: "6.4 inch",
//       camera: "108MP Quad",
//       battery: "4500mAh",
//       processor: "Snapdragon 720G",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/2f/97/34/2f9734ac888fca0cb90d7446bd772bd0.jpg",
//       name: "Realme C31",
//       description:
//         "The Realme C31 features a 6.5-inch display and a triple-camera setup, offering good features for budget users.",
//       ram: "3GB",
//       rom: "32GB",
//       price: "20,000 PKR",
//       display: "6.5 inch",
//       camera: "13MP Triple",
//       battery: "5000mAh",
//       processor: "Unisoc T612",
//       year: "2022",
//     },
  
//     {
//       img: "https://i.pinimg.com/236x/f5/8d/e7/f58de7b3afb855b872b9ab19b33a8adc.jpg",
//       name: "OnePlus 10 Pro",
//       description:
//         "OnePlus 10 Pro features a 6.7-inch Fluid AMOLED display and a triple-camera setup, powered by the Snapdragon 8 Gen 1 for smooth performance.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "200,000 PKR",
//       display: "6.7 inch",
//       camera: "48MP Triple",
//       battery: "5000mAh",
//       processor: "Snapdragon 8 Gen 1",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/0e/9d/1d/0e9d1de36e58276adc1c1891359228a6.jpg",
//       name: "OnePlus Nord 2",
//       description:
//         "OnePlus Nord 2 offers a 6.43-inch Fluid AMOLED display and a 50MP camera, balancing performance and price for mid-range users.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "55,000 PKR",
//       display: "6.43 inch",
//       camera: "50MP Triple",
//       battery: "4500mAh",
//       processor: "Dimensity 1200",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/02/99/32/029932d67d3100eba7a430db76763917.jpg",
//       name: "OnePlus 9",
//       description:
//         "OnePlus 9 features a 6.55-inch Fluid AMOLED display and a Hasselblad camera partnership for stunning photography.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "150,000 PKR",
//       display: "6.55 inch",
//       camera: "48MP Triple",
//       battery: "4500mAh",
//       processor: "Snapdragon 888",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/42/f5/12/42f5122d3b928d121ec9c28e1af3d69c.jpg",
//       name: "OnePlus 8T",
//       description:
//         "The OnePlus 8T comes with a 6.55-inch Fluid AMOLED display and a 48MP quad-camera system, delivering great performance with fast charging.",
//       ram: "12GB",
//       rom: "256GB",
//       price: "90,000 PKR",
//       display: "6.55 inch",
//       camera: "48MP Quad",
//       battery: "4500mAh",
//       processor: "Snapdragon 865",
//       year: "2020",
//     },
//     {
//       img: "https://i.pinimg.com/474x/03/01/17/030117af6349c2ba3a6fa3e439a5ca9c.jpg",
//       name: "OnePlus Nord CE 2",
//       description:
//         "OnePlus Nord CE 2 features a 6.43-inch AMOLED display and a 64MP camera, providing a great balance of features for a mid-range smartphone.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "42,000 PKR",
//       display: "6.43 inch",
//       camera: "64MP Triple",
//       battery: "4500mAh",
//       processor: "Dimensity 900",
//       year: "2022",
//     },
  
//     {
//       img: "https://i.pinimg.com/236x/7c/55/e1/7c55e15281e9fcb9d71de93fcea780fa.jpg",
//       name: "Oppo Find X5 Pro",
//       description:
//         "Oppo Find X5 Pro features a 6.7-inch AMOLED display and a 50MP triple-camera setup. It's powered by the Snapdragon 8 Gen 1 for high-end performance.",
//       ram: "12GB",
//       rom: "256GB",
//       price: "230,000 PKR",
//       display: "6.7 inch",
//       camera: "50MP Triple",
//       battery: "5000mAh",
//       processor: "Snapdragon 8 Gen 1",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/b5/64/01/b5640111602ae996fab5617f86741432.jpg",
//       name: "Oppo Reno 8 Pro",
//       description:
//         "The Oppo Reno 8 Pro features a 6.7-inch AMOLED display and a 50MP camera with advanced imaging capabilities, powered by the MediaTek Dimensity 8100.",
//       ram: "8GB",
//       rom: "256GB",
//       price: "80,000 PKR",
//       display: "6.7 inch",
//       camera: "50MP Triple",
//       battery: "4500mAh",
//       processor: "Dimensity 8100",
//       year: "2022",
//     },
//     {
//       img: "https://i.pinimg.com/236x/d9/ba/d8/d9bad87a011371ce280314b88ea2ce82.jpg",
//       name: "Oppo A54",
//       description:
//         "Oppo A54 comes with a 6.51-inch display and a 13MP camera, providing good features for budget-conscious users.",
//       ram: "4GB",
//       rom: "128GB",
//       price: "28,000 PKR",
//       display: "6.51 inch",
//       camera: "13MP Triple",
//       battery: "5000mAh",
//       processor: "Helio P35",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/2f/d9/90/2fd990d4805f640bae3572ec8ea43a94.jpg",
//       name: "Oppo F19 Pro",
//       description:
//         "Oppo F19 Pro features a 6.43-inch AMOLED display and a 48MP camera, making it a solid mid-range option with good performance.",
//       ram: "8GB",
//       rom: "128GB",
//       price: "40,000 PKR",
//       display: "6.43 inch",
//       camera: "48MP Quad",
//       battery: "4310mAh",
//       processor: "Helio P95",
//       year: "2021",
//     },
//     {
//       img: "https://i.pinimg.com/236x/66/4b/af/664baf101a3ec02c55ca217a0526ff27.jpg",
//       name: "Oppo A74 5G",
//       description:
//         "The Oppo A74 5G features a 6.5-inch AMOLED display and a 48MP camera, offering 5G connectivity at an affordable price.",
//       ram: "6GB",
//       rom: "128GB",
//       price: "45,000 PKR",
//       display: "6.5 inch",
//       camera: "48MP Triple",
//       battery: "5000mAh",
//       processor: "Snapdragon 480",
//       year: "2021",
//     },
//   ]

export default Products;